import type { QuestionRow } from './rationament-analitic'

const items: Omit<QuestionRow, 'institution'>[] = [
  {
    category: 'vocabular',
    question_text: 'Care dintre cuvintele de mai jos este sinonim cu PERSPICACE?',
    options: ['Obtuz', 'Acerb', 'Sagace', 'Inept'],
    correct_answer: 2,
    explanation: 'Perspicace = cu capacitate mare de înțelegere, pătrunzător. Sinonim: sagace (cu judecată ascuțită, înțelept).',
    difficulty: 2,
    metadata: {},
    is_active: true,
  },
  {
    category: 'vocabular',
    question_text: 'Care dintre cuvintele de mai jos este ANTONIM pentru AUSTER?',
    options: ['Sever', 'Lavish', 'Extravagant', 'Îngăduitor'],
    correct_answer: 2,
    explanation: 'Auster = sobru, sever, lipsit de ornamente. Antonim: extravagant (excesiv, ostentativ).',
    difficulty: 2,
    metadata: {},
    is_active: true,
  },
  {
    category: 'vocabular',
    question_text: 'Cuvântul AMBIGUITATE se referă la:',
    options: [
      'Capacitatea de a executa două sarcini simultan',
      'Caracterul dublu sau incert al unui enunț care poate fi interpretat în mai multe moduri',
      'Sentimentul de nehotărâre în fața unei alegeri dificile',
      'Coexistența unor sentimente opuse față de aceeași persoană',
    ],
    correct_answer: 1,
    explanation: 'Ambiguitatea este proprietatea unui enunț, simbol sau situație de a admite mai multe interpretări. Nu trebuie confundat cu ambivalența (coexistența sentimentelor opuse).',
    difficulty: 2,
    metadata: {},
    is_active: true,
  },
  {
    category: 'vocabular',
    question_text: 'Care este definiția corectă a termenului HEURISTIC?',
    options: [
      'Referitor la metode de căutare a adevărului prin descoperire progresivă și explorare',
      'Referitor la studiul sistematic al erorilor de raționament',
      'Referitor la analiza formală a argumentelor valide',
      'Referitor la tehnicile de memorare mnemonică',
    ],
    correct_answer: 0,
    explanation: 'Heuristic provine din gr. heuriskein (a descoperi). Desemnează metode de rezolvare prin explorare, încercare-eroare sau reguli empirice, fără garanția găsirii soluției optime.',
    difficulty: 3,
    metadata: {},
    is_active: true,
  },
  {
    category: 'vocabular',
    question_text: 'Care cuvânt este sinonim cu RETICENT?',
    options: ['Elocvent', 'Ezitant', 'Rezervat', 'Taciturn'],
    correct_answer: 2,
    explanation: 'Reticent = care se abține să exprime deschis opinii sau informații, rezervat. Sinonim: rezervat. Taciturn înseamnă puțin vorbăreț, nu neapărat reticent.',
    difficulty: 2,
    metadata: {},
    is_active: true,
  },
  {
    category: 'vocabular',
    question_text: 'Termenul EPICENTRU este folosit corect în care din propozițiile de mai jos?',
    options: [
      'Epicentrul discuției a fost chestiunea bugetului.',
      'Epicentrul cutremurului s-a aflat la 15 km adâncime.',
      'Epicentrul cutremurului a fost localizat la suprafața scoarței terestre.',
      'Epicentrul problemei constă în lipsa de comunicare.',
    ],
    correct_answer: 2,
    explanation: 'Epicentrul este punctul de la suprafața pământului aflat direct deasupra focarului (hipocentrului) unui cutremur. Nu trebuie confundat cu hipocentrul (focarul din adâncime).',
    difficulty: 2,
    metadata: {},
    is_active: true,
  },
  {
    category: 'vocabular',
    question_text: 'Ce înseamnă PROLIFIC?',
    options: [
      'Care produce puțin, rar',
      'Care produce mult și rapid',
      'Care are calități excepționale',
      'Care imită alte opere',
    ],
    correct_answer: 1,
    explanation: 'Prolific = foarte productiv, care produce mult (opere, idei, descendenți). Din lat. proles (urmași) + facere (a face).',
    difficulty: 1,
    metadata: {},
    is_active: true,
  },
  {
    category: 'vocabular',
    question_text: 'Care este antonimul cuvântului PERENĂ?',
    options: ['Durabilă', 'Sezonală', 'Universală', 'Efemeră'],
    correct_answer: 3,
    explanation: 'Peren/Perenă = care durează mereu, permanent. Antonim: efemerism, efemer = de scurtă durată, trecător.',
    difficulty: 2,
    metadata: {},
    is_active: true,
  },
  {
    category: 'vocabular',
    question_text: 'Expresia AD HOC înseamnă:',
    options: [
      'Conform cu regulile stabilite',
      'Creat sau destinat special pentru o situație particulară',
      'Prin forța argumentului',
      'Conform cu natura lucrului',
    ],
    correct_answer: 1,
    explanation: 'Ad hoc (lat.) = pentru aceasta. Desemnează ceva creat, improvizat sau destinat strict pentru o situație specifică, fără aplicabilitate generală.',
    difficulty: 2,
    metadata: {},
    is_active: true,
  },
  {
    category: 'vocabular',
    question_text: 'INCOERENT înseamnă:',
    options: [
      'Lipsit de logică sau legătură internă',
      'Excesiv de detaliat',
      'Extrem de dens sau comprimat',
      'Lipsit de claritate vizuală',
    ],
    correct_answer: 0,
    explanation: 'Incoerent = fără coerență, fără legătură logică sau structurală. Opusul unui discurs sau sistem coerent (bine articulat intern).',
    difficulty: 1,
    metadata: {},
    is_active: true,
  },
  {
    category: 'vocabular',
    question_text: 'Care dintre cuvintele de mai jos desemnează cel mai bine sensul lui APOCRIF?',
    options: [
      'Autentic și certificat oficial',
      'De origine îndoielnică, nerecunoscut ca autentic',
      'Extrem de rar și valoros',
      'Accesibil doar inițiaților',
    ],
    correct_answer: 1,
    explanation: 'Apocrif = text sau operă a cărei autenticitate sau origine este contestată. Din gr. apokryphos = ascuns, secret.',
    difficulty: 3,
    metadata: {},
    is_active: true,
  },
  {
    category: 'vocabular',
    question_text: 'Termenul TAUTOLOGIE se referă la:',
    options: [
      'O afirmație care se contrazice pe sine',
      'O afirmație redundantă care repetă același lucru în cuvinte diferite',
      'O afirmație care nu poate fi nici adevărată nici falsă',
      'O afirmație bazată pe o premisă falsă',
    ],
    correct_answer: 1,
    explanation: 'Tautologia este o formulare care repetă același conținut în termeni diferiți (ex: "copil minor", "ucis la moarte"). În logică, o propoziție care este adevărată prin forma sa.',
    difficulty: 3,
    metadata: {},
    is_active: true,
  },
  {
    category: 'vocabular',
    question_text: 'Ce înseamnă LACONIC?',
    options: [
      'Confuz și neclar',
      'Exprimat în puține cuvinte, concis',
      'Plin de detalii inutile',
      'Extrem de formal și rigid',
    ],
    correct_answer: 1,
    explanation: 'Laconic = care folosește puține cuvinte, concis, sobru în exprimare. Provine de la spartanii din Laconia, faimoși pentru stilul scurt de comunicare.',
    difficulty: 2,
    metadata: {},
    is_active: true,
  },
  {
    category: 'vocabular',
    question_text: 'DEDUCTIV înseamnă:',
    options: [
      'Care pornește de la cazuri particulare spre o regulă generală',
      'Care pornește de la o regulă generală spre un caz particular',
      'Care se bazează pe observarea repetată a fenomenelor',
      'Care formulează ipoteze fără a le verifica',
    ],
    correct_answer: 1,
    explanation: 'Raționamentul deductiv merge de la general la particular (dacă premisele sunt adevărate și forma este validă, concluzia este cert adevărată). Spre deosebire de inductiv (de la particular la general).',
    difficulty: 2,
    metadata: {},
    is_active: true,
  },
  {
    category: 'vocabular',
    question_text: 'Care cuvânt este sinonim cu ACERBITATE?',
    options: ['Blândețe', 'Asprime', 'Indiferență', 'Resemnare'],
    correct_answer: 1,
    explanation: 'Acerbitate = asprime extremă, severitate dură, caracter acid. Sinonim: asprime, duritate.',
    difficulty: 3,
    metadata: {},
    is_active: true,
  },
]

export function generateVocabular(institution: string): QuestionRow[] {
  return items.map(item => ({ ...item, institution }))
}
